# Generated by Django 5.2.5 on 2025-08-26 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=12)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_encounters', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='SoapNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soap', to='chart.encounter')),
            ],
        ),
    ]
