# Generated by Django 5.2.5 on 2025-08-27 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance_system', models.CharField(default='http://snomed.info/sct', max_length=64)),
                ('substance_code', models.CharField(blank=True, default='', max_length=32)),
                ('substance_display', models.CharField(blank=True, default='', max_length=256)),
                ('status', models.CharField(default='active', max_length=24)),
                ('severity', models.CharField(blank=True, default='', max_length=16)),
                ('reaction_text', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_allergies', to='patients.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'status'], name='chart_aller_patient_be8b84_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConditionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_system', models.CharField(default='http://snomed.info/sct', max_length=64)),
                ('code', models.CharField(blank=True, default='', max_length=32)),
                ('display', models.CharField(blank=True, default='', max_length=256)),
                ('clinical_status', models.CharField(default='active', max_length=24)),
                ('verification_status', models.CharField(default='confirmed', max_length=24)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('abatement_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_conditions', to='chart.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_conditions', to='patients.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'clinical_status'], name='chart_condi_patient_2b972d_idx')],
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_system', models.CharField(default='http://loinc.org', max_length=64)),
                ('code', models.CharField(max_length=32)),
                ('display', models.CharField(blank=True, default='', max_length=128)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='', max_length=32)),
                ('effective_time', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_vitals', to='chart.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_vitals', to='patients.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['encounter', 'patient', 'code'], name='chart_vital_encount_322988_idx')],
            },
        ),
    ]
