# Generated by Django 5.2.5 on 2025-08-23 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dos', models.DateField()),
                ('mode', models.CharField(choices=[('SIMULATED', 'SIMULATED'), ('MANUAL', 'MANUAL'), ('REAL', 'REAL')], default='SIMULATED', max_length=12)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.coverage')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
