# Generated by Django 5.2.5 on 2025-08-26 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('chart', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superbill',
            name='encounter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='superbill', to='chart.encounter'),
        ),
        migrations.AddField(
            model_name='superbill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_superbills', to='patients.patient'),
        ),
    ]
