# Generated by Django 5.2.5 on 2025-08-27 23:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('registry', '0003_coverage_cob_order_coverage_coverage_class_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperbillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('mod1', models.CharField(blank=True, default='', max_length=2)),
                ('mod2', models.CharField(blank=True, default='', max_length=2)),
                ('mod3', models.CharField(blank=True, default='', max_length=2)),
                ('mod4', models.CharField(blank=True, default='', max_length=2)),
                ('units', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dx_ptrs', models.JSONField(blank=True, default=list)),
                ('pos', models.CharField(blank=True, default='', max_length=4)),
                ('auth_number', models.CharField(blank=True, default='', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('rendering_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendered_lines', to='registry.provider')),
                ('superbill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_lines', to='billing.superbill')),
            ],
            options={
                'indexes': [models.Index(fields=['superbill', 'code'], name='billing_sup_superbi_d1b601_idx')],
            },
        ),
    ]
