# Generated by Django 5.2.5 on 2025-08-28 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_superbillline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimResponseStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('superbill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim_response', to='billing.superbill')),
            ],
        ),
    ]
