# Generated by Django 5.2.5 on 2025-08-27 01:49

import apps.registry.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='coinsurance_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percent 0-100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='copay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='deductible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='oop_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='ssn',
            field=models.CharField(blank=True, default='', max_length=11, validators=[apps.registry.validators.validate_ssn]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='npi',
            field=models.CharField(blank=True, default='', max_length=15, validators=[apps.registry.validators.validate_npi]),
        ),
    ]
