# Generated by Django 5.2.5 on 2025-08-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('registry', '0002_alter_coverage_coinsurance_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverage',
            name='cob_order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coverage',
            name='coverage_class_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='coverage',
            name='extensions_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='coverage',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='coverage',
            name='network',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='coverage',
            name='payer_contact_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='coverage',
            name='plan_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='coverage',
            name='rx_bin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='coverage',
            name='rx_group',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='coverage',
            name='rx_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='coverage',
            name='rx_pcn',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='coverage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('patient',), name='uniq_primary_coverage_per_patient'),
        ),
    ]
