# Generated by Django 5.2.5 on 2025-08-28 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_coverage_cob_order_coverage_coverage_class_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderDEARegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dea_number', models.CharField(max_length=20)),
                ('schedules', models.JSONField(blank=True, default=list)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dea_regs', to='registry.provider')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'dea_number'], name='registry_pr_provide_a4a49d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProviderLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('number', models.CharField(max_length=50)),
                ('license_type', models.CharField(blank=True, default='', max_length=40)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='registry.provider')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'state', 'expiry'], name='registry_pr_provide_c16417_idx')],
            },
        ),
    ]
