# Generated by Django 5.2.5 on 2025-08-28 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_providerdearegistration_providerlicense'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(blank=True, default='', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='registry.facility')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='registry.provider')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'facility'], name='registry_pr_provide_0f193b_idx')],
            },
        ),
    ]
