# Generated by Django 5.2.5 on 2025-08-23 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareSetting',
            fields=[
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('pos_codes', models.JSONField(blank=True, default=list)),
                ('cms_provider_type', models.CharField(blank=True, max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='clinical_directory.caresetting')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('nucc_code', models.CharField(blank=True, max_length=20)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='clinical_directory.specialty')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=180)),
                ('npi', models.CharField(blank=True, max_length=10)),
                ('tin', models.CharField(blank=True, max_length=20)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('care_setting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinical_directory.caresetting')),
                ('specialties', models.ManyToManyField(blank=True, to='clinical_directory.specialty')),
            ],
        ),
    ]
