# Generated by Django 5.2.5 on 2025-08-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(blank=True, max_length=120)),
                ('file_name', models.CharField(max_length=200)),
                ('file_hash', models.CharField(max_length=64)),
                ('format', models.CharField(max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
