# Generated by Django 5.2.5 on 2025-08-24 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=160)),
                ('naic_code', models.CharField(blank=True, max_length=20)),
                ('payer_id', models.CharField(blank=True, max_length=40)),
                ('trading_partner_id', models.CharField(blank=True, max_length=60)),
                ('edi_eligibility_receiver_id', models.CharField(blank=True, max_length=40)),
                ('edi_claim_receiver_id', models.CharField(blank=True, max_length=40)),
                ('pa_portal_url', models.URLField(blank=True)),
                ('claims_portal_url', models.URLField(blank=True)),
                ('service_states', models.JSONField(blank=True, default=list)),
                ('contact', models.JSONField(blank=True, default=dict)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='PayerPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('product_type', models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('HMO', 'HMO'), ('PPO', 'PPO'), ('EPO', 'EPO'), ('POS', 'POS'), ('MA', 'Medicare Advantage'), ('MEDICAID', 'Medicaid'), ('EXCHANGE', 'ACA Exchange'), ('DENTAL', 'Dental'), ('VISION', 'Vision'), ('PHARMACY', 'Pharmacy')], default='COMMERCIAL', max_length=20)),
                ('plan_id', models.CharField(blank=True, max_length=60)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='rcm.payer')),
            ],
            options={
                'unique_together': {('payer', 'name', 'product_type')},
            },
        ),
    ]
