# Generated by Django 5.2.5 on 2025-08-28 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcm', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payerplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payerplan',
            name='network_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='payerplan',
            name='payer_id_str',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='payerplan',
            name='payer_label',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='payerplan',
            name='name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='payerplan',
            name='plan_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=160)),
                ('scope', models.CharField(choices=[('LINE', 'LINE'), ('CLAIM', 'CLAIM')], default='LINE', max_length=8)),
                ('payer_id_str', models.CharField(blank=True, default='', max_length=64)),
                ('cpt_code', models.CharField(blank=True, default='', max_length=10)),
                ('pos_allowed', models.JSONField(blank=True, default=list)),
                ('modifiers_required', models.JSONField(blank=True, default=list)),
                ('dx_required_any', models.JSONField(blank=True, default=list)),
                ('dx_allowed', models.JSONField(blank=True, default=list)),
                ('provider_taxonomy_allowed', models.JSONField(blank=True, default=list)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sex_allowed', models.JSONField(blank=True, default=list)),
                ('message', models.CharField(blank=True, default='', max_length=240)),
                ('severity', models.CharField(choices=[('BLOCK', 'BLOCK'), ('WARN', 'WARN')], default='WARN', max_length=8)),
                ('effective_start', models.DateField(blank=True, null=True)),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('payer_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='rcm.payerplan')),
            ],
        ),
        migrations.RemoveField(
            model_name='payerplan',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='payerplan',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='payerplan',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='Payer',
        ),
    ]
