# Generated by Django 5.2.5 on 2025-08-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical_directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id_stable', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=160)),
                ('help_text', models.TextField(blank=True)),
                ('ui_type', models.CharField(default='text', max_length=40)),
                ('intake_steps', models.JSONField(default=list)),
                ('required', models.CharField(default='N', max_length=1)),
                ('privacy_flags', models.JSONField(blank=True, default=list)),
                ('fhir_map', models.CharField(blank=True, max_length=200)),
                ('value_set', models.JSONField(blank=True, default=dict)),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('order', models.IntegerField(default=1000)),
                ('active', models.BooleanField(default=True)),
                ('specialties', models.ManyToManyField(blank=True, to='clinical_directory.specialty')),
            ],
        ),
    ]
