# Generated by Django 5.2.5 on 2025-08-23 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('encounter_id', models.IntegerField(blank=True, null=True)),
                ('payer_name', models.CharField(max_length=120)),
                ('billing_provider_npi', models.CharField(max_length=10)),
                ('rendering_provider_npi', models.CharField(max_length=10)),
                ('facility_name', models.CharField(blank=True, max_length=160)),
                ('pos', models.CharField(max_length=2)),
                ('auth_number', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(default='DRAFT', max_length=24)),
                ('total_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('claim_control_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpt', models.CharField(max_length=10)),
                ('modifiers', models.JSONField(blank=True, default=list)),
                ('units', models.DecimalField(decimal_places=2, default=1, max_digits=7)),
                ('diagnosis_pointers', models.JSONField(blank=True, default=list)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('npi_override', models.CharField(blank=True, max_length=10)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='claims.claim')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('order', models.PositiveSmallIntegerField()),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='claims.claim')),
            ],
        ),
        migrations.CreateModel(
            name='ScrubFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('severity', models.CharField(max_length=8)),
                ('message', models.TextField()),
                ('suggestion', models.TextField(blank=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='claims.claim')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='claims.claimline')),
            ],
        ),
    ]
