# Generated by Django 5.2.5 on 2025-08-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('max_units', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='NCCIEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_primary', models.CharField(max_length=20)),
                ('code_secondary', models.CharField(max_length=20)),
                ('edit_type', models.CharField(default='PAIR', max_length=20)),
            ],
            options={
                'unique_together': {('code_primary', 'code_secondary', 'edit_type')},
            },
        ),
    ]
