# Generated by Django 5.2.5 on 2025-08-23 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_mue_ncciedit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoFixAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('preview', 'preview'), ('apply', 'apply')], max_length=12)),
                ('flags', models.JSONField(blank=True, default=dict)),
                ('proposed', models.JSONField(blank=True, default=list)),
                ('committed', models.JSONField(blank=True, default=list)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autofix_audits', to='claims.claim')),
            ],
        ),
    ]
