# Generated by Django 5.2.5 on 2025-08-23 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_autofixaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdiExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=300)),
                ('sha256', models.CharField(max_length=64)),
                ('interchange_id', models.CharField(blank=True, max_length=30)),
                ('functional_id', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('SENT', 'SENT'), ('FAILED', 'FAILED')], default='QUEUED', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edi_exports', to='claims.claim')),
            ],
        ),
    ]
