# Generated by Django 5.2.5 on 2025-08-25 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_eraimport_denial_adjustment_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenialStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('denial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='claims.denial')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
