# Generated by Django 5.2.5 on 2025-08-23 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSystem',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('version', models.CharField(blank=True, max_length=40)),
                ('source_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('display', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='codes.codesystem')),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='codes_code_code_74bcb1_idx'), models.Index(fields=['display'], name='codes_code_display_045f52_idx')],
                'unique_together': {('system', 'code')},
            },
        ),
    ]
