# Generated by Django 5.2.5 on 2025-08-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='system',
            field=models.CharField(choices=[('ICD10', 'ICD-10-CM'), ('CPT', 'CPT')], max_length=16),
        ),
        migrations.RemoveIndex(
            model_name='code',
            name='codes_code_code_74bcb1_idx',
        ),
        migrations.RemoveIndex(
            model_name='code',
            name='codes_code_display_045f52_idx',
        ),
        migrations.RemoveField(
            model_name='code',
            name='active',
        ),
        migrations.RemoveField(
            model_name='code',
            name='display',
        ),
        migrations.AddField(
            model_name='code',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='code',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=16),
        ),
        migrations.AddIndex(
            model_name='code',
            index=models.Index(fields=['system', 'code'], name='codes_code_system_ed0586_idx'),
        ),
        migrations.AddIndex(
            model_name='code',
            index=models.Index(fields=['description'], name='codes_code_descrip_2d31ee_idx'),
        ),
        migrations.DeleteModel(
            name='CodeSystem',
        ),
    ]
